//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ChilliSource Core")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha.24+Branch.develop.Sha.50cebc4ace73176165754696e62d36ce499403d0")]
[assembly: AssemblyCopyright("Copyright (c) BlueChilli Technology PTY LTD")]

